#cloud-config
autoinstall:
  version: 1
  locale: en_US
  keyboard:
    layout: "us,ru"
    toggle: alt_shift_toggle
  disk:
    target: /dev/sda
    wipe: auto
    partitions:
      - number: 1
        size: 20GB
        format: ext4
        filesystem: ext4
        mount: /
      - number: 2
        size: 8GB
        format: swap
        filesystem: swap
  user-data:
    install_desktop: xubuntu-desktop-minimal
    packages:
      - git
      - php
      - perl
      - mysql-server
      - mysql-client
      - apache2
