#cloud-config python3 -m http.server 8000 && xdg-open http://localhost:8000/autoinstall/autoinstall.yaml

autoinstall:
  version: 1
  locale: ru_RU.UTF-8
  keyboard:
    layout: ru
  network:
    version: 2
    ethernets:
      enp0s3:
        dhcp4: true
  storage:
    layout:
      name: lvm
  identity:
    hostname: xubuntu-server
  user-data:
    disable_root: false
    users:
      - name: user01
        passwd: "$6$rounds=4096$salt$hash"  # Замените на реальный хеш
        shell: /bin/bash
        groups: [adm, cdrom, sudo, dip, plugdev, lxd]
        lock-passwd: false
        sudo: "ALL=(ALL) NOPASSWD:ALL"
      - name: user02
        passwd: "$6$rounds=4096$salt$hash"  # Тот же хеш
        shell: /bin/bash
        groups: [adm, cdrom, sudo, dip, plugdev, lxd]
        lock-passwd: false
        sudo: "ALL=(ALL) NOPASSWD:ALL"
      - name: user03
        passwd: "$6$rounds=4096$salt$hash"  # Тот же хеш
        shell: /bin/bash
        groups: [adm, cdrom, sudo, dip, plugdev, lxd]
        lock-passwd: false
        sudo: "ALL=(ALL) NOPASSWD:ALL"
  
  packages:
    # Существующие пакеты
    - openssh-server
    - apache2
    - mysql-server
    - php
    - libapache2-mod-php
    - php-mysql
    - phpmyadmin
    - vsftpd
    - filezilla
    - ufw
    - git
    - curl
    - wget
    - neovim
    - python3
    - rustup
    - openvpn
    - easy-rsa
    - tigervnc-standalone-server
    - tigervnc-common
    - expect
    
    # Добавленные пакеты по запросу
    - lm-sensors
    - hwinfo
    - smartmontools
    - sysstat
    - zbar-tools
    - qtqr
    - libsane
    - sane-utils
    - cups
    - cups-bsd
    - printer-driver-gutenprint
    - build-essential
    - htop
    - iotop
    - nmon
    - stress
    - libusb-dev
    - libhidapi-dev

  late-commands:
    # [Остальные команды из предыдущей конфигурации остаются без изменений]
    # ... (FTP, OpenVPN, VNC, SSH, MySQL, Firewall)
    
    # Установка дополнительных компонентов для работы с оборудованием
    - |
      # Для сканеров биометрии (общие зависимости)
      in-target apt-get install -y libfprint-dev libpam-fprint
      
      # Драйверы для кассовых аппаратов
      in-target wget https://download.epson-biz.com/modules/pos/index.php?page=soft&scat=58 -O /tmp/epson-pos.tar.gz
      in-target tar -xzf /tmp/epson-pos.tar.gz -C /opt/
      
      # Для принтеров штрихкодов
      in-target git clone https://github.com/zint/zint.git /opt/zint
      in-target /bin/bash -c "cd /opt/zint && mkdir build && cd build && cmake .. && make && make install"
      
      # Инструменты для сборки ПК
      in-target pip3 install pc-part-parser
      
      # Библиотеки для работы с QR-кодами
      in-target pip3 install qrcode[pil] pyzbar
      
      # Дополнительные диагностические утилиты
      in-target apt-get install -y inxi dmidecode gddrescue memtester

    # Настройка CUPS для принтеров
    - |
      in-target usermod -aG lpadmin user01
      in-target usermod -aG lpadmin user02
      in-target usermod -aG lpadmin user03
      in-target systemctl enable cups

    # Разрешение USB-устройств для пользователей
    - |
      echo 'SUBSYSTEM=="usb", MODE="0666", GROUP="users"' > /target/etc/udev/rules.d/99-com.rules